### ISSUE TITLE
no get_enemies in the amidar API

### ISSUE THREAD

**Issue by etosch** [toybox-rs/Toybox#125]
adding this locally. the idea is to be able to run:

```
with AmidarIntervention(tb) as ai:
    for enemy in ai.get_enemies():
       enemy.set_enemy_protocol('foo')
```

**Comment by kclary** [comment]
There is a `set_enemy_protocols` for setting protocols of multiple enemies, and you could use `num_enemies` if you want to loop over them. Am I misunderstanding?

**Comment by kclary** [comment]
Ok to close?

**Comment by jjfiv** [comment]
#150
