### ISSUE TITLE
Make gridworld string-based

### ISSUE THREAD

**Issue by kclary** [toybox-rs/Toybox#131]
Unify state/config string representations for gridworld boards

**Comment by jjfiv** [comment]
:-1: for title.

**Comment by jjfiv** [comment]
33986cb1cb78fefee2e7ba2a35ae6e34dbe93dad

**Comment by jjfiv** [comment]
Also:
 - [ ] Gridworld moving enemies.
 - [ ] Gridworld buttons (make some tile not movable?)

**Comment by jjfiv** [comment]
long-term: wontfix (more like won't-merge: #131)
