### ISSUE TITLE
Tensorflow/tensorboard requirements

### ISSUE THREAD

**Issue by agentzel** [toybox-rs/Toybox#145]
The requirements file for Toybox lists tensorflow<2.0.0 and tensorboard<2.1.0,>=2.0.0.  However, after installing tensorflow 1.1.15, trying to install tensorboard 2.0.1 produces an error:

ERROR: tensorflow 1.15.0 has requirement tensorboard<1.16.0,>=1.15.0, but you'll have tensorboard 2.0.1 which is incompatible.

**Comment by etosch** [comment]
Currently have less strict tensorboard requirements.
