### ISSUE TITLE
Error when running Toybox locally

### ISSUE THREAD

**Issue by agentzel** [toybox-rs/Toybox#146]
When trying to run the command `./start_python -m baselines.run --alg=acktr --seed=2921082615 -env=AmidarToyboxNoFrameskip-v4 --num_timesteps=5e7`, I get the following error:

> PYTHONPATH /Users/agentzel/Documents/workspace/Toybox/ctoybox/baselines:/Users/agentzel/Documents/workspace/Toybox/ctoybox/toybox:
> LD_LIBRARY_PATH :/Users/agentzel/Documents/workspace/Toybox/ctoybox/../target/release
> LIBCTOYBOX /Users/agentzel/Documents/workspace/Toybox/ctoybox/..
> Global setup not found...trying local development install...
> Looking for toybox lib in
> 	/Users/agentzel/Documents/workspace/Toybox/ctoybox/../target/debug/libctoybox.dylib
> or
> 	/Users/agentzel/Documents/workspace/Toybox/ctoybox/../target/release/libctoybox.dylib
> /Users/agentzel/Documents/workspace/Toybox/ctoybox/../target/release/libctoybox.dylib
> Registered Toybox environments with gym.
> Logging to /var/folders/4x/j0n9zj2j7lb33wwghlgzj_5c0000gq/T/openai-2019-12-17-16-11-49-716768
> Logging to /var/folders/4x/j0n9zj2j7lb33wwghlgzj_5c0000gq/T/openai-2019-12-17-16-11-51-401334
> env_type: mujoco
> Traceback (most recent call last):
>   File "/Users/agentzel/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/Users/agentzel/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/Users/agentzel/Documents/workspace/Toybox/ctoybox/baselines/baselines/run.py", line 253, in <module>
>     main()
>   File "/Users/agentzel/Documents/workspace/Toybox/ctoybox/baselines/baselines/run.py", line 200, in main
>     model, env = train(args, extra_args)
>   File "/Users/agentzel/Documents/workspace/Toybox/ctoybox/baselines/baselines/run.py", line 69, in train
>     learn = get_learn_function(args.alg)
>   File "/Users/agentzel/Documents/workspace/Toybox/ctoybox/baselines/baselines/run.py", line 158, in get_learn_function
>     return get_alg_module(alg).learn
>   File "/Users/agentzel/Documents/workspace/Toybox/ctoybox/baselines/baselines/run.py", line 152, in get_alg_module
>     alg_module = import_module('.'.join(['baselines', alg, submodule]))
>   File "/Users/agentzel/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/Users/agentzel/Documents/workspace/Toybox/ctoybox/baselines/baselines/acktr/acktr.py", line 1, in <module>
>     from baselines.acktr.acktr_disc import *
>   File "/Users/agentzel/Documents/workspace/Toybox/ctoybox/baselines/baselines/acktr/acktr_disc.py", line 9, in <module>
>     from baselines.common.policies import build_policy
>   File "/Users/agentzel/Documents/workspace/Toybox/ctoybox/baselines/baselines/common/policies.py", line 7, in <module>
>     from baselines.common.mpi_running_mean_std import RunningMeanStd
>   File "/Users/agentzel/Documents/workspace/Toybox/ctoybox/baselines/baselines/common/mpi_running_mean_std.py", line 1, in <module>
>     from mpi4py import MPI
> ImportError: dlopen(/Users/agentzel/anaconda3/lib/python3.7/site-packages/mpi4py/MPI.cpython-37m-darwin.so, 2): Symbol not found: ___addtf3
>   Referenced from: /usr/local/opt/gcc/lib/gcc/9/libquadmath.0.dylib
>   Expected in: /usr/lib/libSystem.B.dylib
>  in /usr/local/opt/gcc/lib/gcc/9/libquadmath.0.dylib

**Comment by kclary** [comment]
> env_type: mujoco
This seems related to #143
