### ISSUE TITLE
RGB observations not working

### ISSUE THREAD

**Issue by Miffyli** [toybox-rs/Toybox#175]
If one sets `alpha=False` and `grayscale=False`, this correctly defines the observation space as having three channels (RGB). However the returned observations are four-channel RGBA. This seems to be a result of directly calling [this](https://github.com/toybox-rs/toybox-rs/blob/master/ctoybox/ctoybox/ffi.py#L449) function without further processing on the observation.

A simple fix would be to check if `self._rgba == 3` and then drop the final channel with `obs = obs[:, :, :-1]`. I could make a PR for this if such solution is alright to you (not too inefficient).

PS: Cheers for a nice project! It is nice to have a chance to change these games at will with clear dictionary names/values :)

**Comment by jjfiv** [comment]
Hi @Miffyli, thanks for finding this. 

We'd happily accept the PR you've described if you want to send it our way. I think slicing out the "a" components is probably going to be efficient enough ... they should all be 255, anyway.
